### PR TITLE
NE-514: Rebase to upstream v1.8.1

### PR DESCRIPTION
**Pull request by sgreene570**
# CoreDNS v1.8.1 rebase process
Inspired by the commit description for the v1.6.6 rebase https://github.com/openshift/coredns/pull/22

As well as by https://github.com/openshift/kubernetes-autoscaler/pull/185

Identify carry commits:

`git log --oneline --no-merges 0858c65b340b205e2831ffb85cb95c14c6bd5266..openshift/master`
where (https://github.com/openshift/coredns/commit/0858c65b340b205e2831ffb85cb95c14c6bd5266) reflects the changes since our last rebase.

Note that the `UPSTREAM: <carry>: openshift:` prefix was added to any new commits to carry since the previous rebase. This will make new carry commits easy to identify alongside prior carry commits.

After identifying the carry commits, the next step is to create the new commit-tree that will be used for the rebase and then cherry pick the carry commits into the new branch.

The following commands cover these steps:

Process

```
$ git remote update # make sure we update our refs
$ git checkout v1.8.1 # upstream CoreDNS 1.8.1 commit tag
$ git checkout -b merge-tmp # create a branch to do our merge work from
$ git checkout openshift/master # we want to be at the tip of the openshift master branch when we run the next command
$ echo 'merge coredns/coredns v1.8.1' | git commit-tree merge-tmp^{tree} -p HEAD -p merge-tmp -F -
deadbeef12345678 # id of new merge commit
$ git branch merge-1.8.1 deadbeef12345678 # create a new branch for the cherry-pick work
$ git checkout merge-1.8.1 # make sure we are on the proper branch
$ git cherry-pick <carry commits>
```

My 1.8.1 merge commit from the above process is (https://github.com/openshift/coredns/commit/e769ec998b66457a687a426b21acf655318e21dd).

With the merge-1.8.1 branch in place, I cherry picked the carry commits. Merge conflicts were resolved on an individual commit basis when necessary. Some commits (eg. vendor changes, or upstream fixes that have merged since our last rebase) were dropped. If there are any questions there please let me know.

Carried Commits (applied bottom to top / oldest first):

```
4a5fb483d UPSTREAM: <carry>: openshift: Vendor required modules (to be replaced in the next rebase)
c8b493bbe UPSTREAM: <carry>: openshift: Updating coredns builder & base images to be consistent with ART Reconciling with https://github.com/openshift/ocp-build-data/tree/5a1293dd0f380abf50c12d65c36655486d7745d0/images/coredns.yml
0fecda9e4 UPSTREAM: <carry>: openshift: Updating coredns builder & base images to be consistent with ART Reconciling with https://github.com/openshift/ocp-build-data/tree/b0ab44b419faae6b18e639e780a1fa50a1df8521/images/coredns.yml
1a98e7b92 UPSTREAM: <carry>: openshift: gitignore: Properly ignore coredns binary
665e4bb8a UPSTREAM: <carry>: openshift: Updating coredns builder & base images to be consistent with ART Reconciling with https://github.com/openshift/ocp-build-data/tree/ac81dd4ff0bd57c4e75058d25b40615b92948259/images/coredns.yml
1462051fa UPSTREAM: <carry>: openshift: Update owners
2fa061a96 UPSTREAM: <carry>: openshift: Updating Dockerfile.openshift.rhel7 baseimages to mach ocp-build-data config
f1c1c7dc2 UPSTREAM: <carry>: openshift: Updating Dockerfile.openshift.rhel7 baseimages to mach ocp-build-data config
12da9afc5 UPSTREAM: <carry>: openshift: OWNERS: Add component
c2d922636 UPSTREAM: <carry>: openshift: Add github.com/openshift/coredns-mdns plugin
07acbeb99 UPSTREAM: <carry>: openshift: Make coredns exclusion more specific
973ad6860 UPSTREAM: <carry>: openshift: Set Dockerfiles to use vendor
a6e80500e UPSTREAM: <carry>: openshift: Add a `make test` target
73e0eb379 UPSTREAM: <carry>: openshift: Optimize COPY directive
40c11e7a7 UPSTREAM: <carry>: openshift: Add a RHEL7 Dockerfile and standardize format
f77295fe6 UPSTREAM: <carry>: openshift: Use multistage builds
394b61745 UPSTREAM: <carry>: openshift: Update metadata
b65c0ca72 UPSTREAM: <carry>: openshift: Add a product build pipeline Dockerfile
ce59f0f55 UPSTREAM: <carry>: openshift: Changed the OWNERS to OpenShift ones
```

Dropped Commits (vendor commits are not necessary, and upstream commits from our fork would be taken care of by the rebase. No need to keep empty commits around).

```
5dec8e11d vendor: Bump for kube 1.20 // DROPPED
56a13f8ed go.mod: Bump for kube 1.20 // DROPPED
283fd1454 vendor: Bump Azure/go-autorest // DROPPED
89b08daba go.mod: Bump Azure/go-autorest // DROPPED
7bf2aa0b8 Remove federation plugin // DROPPED
59fab1734 Kubernetes plugin fixes for kube 1.18 API bump // DROPPED
27af8bcc9 Update kubernetes plugin object.go for kube 1.17 // DROPPED
9d7cda6d9 vendor: Bump deps for kube 1.19 // DROPPED
1f4fb828b go.mod: Bump deps for kube 1.19 // DROPPED
1689a12d8 plugin/kubernetes: Handle endpoint tombstones (#3887) // DROPPED
6116f47bb Bug 1860142: Adds HealthcheckBrokenCount to forward plugin // DROPPED
a9a2519fa Vendor latest golang.org/x/text // DROPPED
3f7b0299c Update vendoring of coredns-mdns // DROPPED
392872f64 Update coredns-mdns vendoring // DROPPED
aeba6024d Update coredns-mdns vendoring // DROPPED
358bd8f4e UPSTREAM: <carry>: openshift: Vendor required modules // DROPPED
5e1e5be0e UPSTREAM: <carry>: openshift: Fix HostPortOrFile to support IPv6 addresses with zone (#3527) // DROPPED
```

---
Prerequisites:

- [x]  https://github.com/openshift/coredns-mdns/pull/73
- [x]   https://github.com/openshift/cluster-dns-operator/pull/238

/cc @bcrochet @cybertron (Thanks for the help, kudos to both of you!)
@openshift/openshift-team-network-edge

### CODE REVIEW

**Comment by sgreene570** [comment]
unit tests are passing on my machine :thinking: 
/test unit

**Comment by sgreene570** [comment]
Once this merges I will cherry pick https://github.com/coredns/coredns/pull/4430 so that CoreDNS pods will watch endpointslices instead of endpoints on OCP.

**Comment by sgreene570** [comment]
> /lgtm

huh, I'm not sure why this didnt apply the lgtm label :thinking:

**Comment by sgreene570** [comment]
CI is all green :grin:

**Comment by cybertron** [comment]
/lgtm

This may not work because of https://github.com/openshift/coredns/pull/52#issuecomment-783620670 Maybe it's not happy because we authored commits? I am a member of the openshift org so that shouldn't be it.

**Pull request merged**
