### PR TITLE
Rebase to upstream 1.6.6

### PR DESCRIPTION
**Pull request by bcrochet**
The PR was created by first taking upstream/v1.6.6 (tag) as the base then applying `UPSTREAM: <carry>` patches on top. The set of patches applied was taken from:

 ```
$ git log --no-merges --format=oneline  v1.6.6..openshift/master  
```

To create the merge commit I have used the following steps:

```
$ git remote update
$ git checkout v1.6.6
$ git checkout -b merge
$ git checkout openshift/master
$ echo 'merge v1.6.6' | git commit-tree merge^{tree} -p HEAD -p merge
deadbeef12345678
$ git checkout deadbeef12345678
$ git cherry-pick ...all-the-things...
$ git checkout -b rebase-to-upstream-1.6.6
```

For details on the `merge^{tree}` syntax please read this [documentation](https://git-scm.com/book/en/v2/Git-Internals-Git-Objects#_tree_objects).

The result of `git commit-tree` in this PR is [0858c65](https://github.com/openshift/coredns/commit/0858c65b340b205e2831ffb85cb95c14c6bd5266)

I then applied all the carry commits on top. Some patches were dropped, because they were referencing old vendored code, and Gopkg.*. A single vendor commit was created to be replaced in future rebases.

As we have not used this method prior, I have added the `UPSTREAM: <carry>: openshift` prefix to those commits that did not have this convention. This will make it easier to identify carry commits for the next rebase.

### CODE REVIEW

**Comment by bcrochet** [comment]
[bcrochet@bcrochet coredns]$ podman build -f Dockerfile.openshift .
STEP 1: FROM registry.svc.ci.openshift.org/openshift/release:golang-1.12 AS builder
STEP 2: WORKDIR /go/src/github.com/coredns/coredns
7aa3ab0b7f015a39852c43f1bf0eab23b0ff5df963fdf450745d3a929797f9aa
STEP 3: COPY . .
e6b1b53cfdfcb306883c59a3d26f3eb3d23ca39b7662012e126f39a264d35959
STEP 4: RUN GO111MODULE=on GOFLAGS=-mod=vendor go build -o coredns .
2020-01-22T13:15:00.000075137Z: cannot configure rootless cgroup using the cgroupfs manager
624b2b6237aacdfd5ee159494c3edcfa8f8da1499d9d1900521465affce77684
STEP 5: FROM registry.svc.ci.openshift.org/openshift/origin-v4.0:base
STEP 6: COPY --from=builder /go/src/github.com/coredns/coredns/coredns /usr/bin/
921662387350668c821fe1ae819be0bf589caa8365a6b8fd433f8bc74333c9f1
STEP 7: ENTRYPOINT ["/usr/bin/coredns"]
0f9ebbf9eba179c7c7bc853d3c8ca7bdd18e8822f124fdd88cb85933bfaa91c8
STEP 8: LABEL io.k8s.display-name="CoreDNS"       io.k8s.description="CoreDNS delivers the DNS and Discovery Service for a Kubernetes cluster."       maintainer="dev@lists.openshift.redhat.com"
STEP 9: COMMIT
933249b1b8476284ceeaec18ca367c02b0eebe798bbfda5aacb8a1f7620ef887
933249b1b8476284ceeaec18ca367c02b0eebe798bbfda5aacb8a1f7620ef887

Image build is working locally.

**Comment by russellb** [comment]
@ironcladlou @bcrochet This PR included some fixes we need for IPv6.  Do you want to propose a backport of the whole rebase?  or cherry-pick the specific things needed for IPv6?

**Comment by ironcladlou** [comment]
I _think_ we should backport the rebase to ease future backports, @bcrochet what do you think? Seems like it should merge cleanly?

**Pull request merged**
