### PR TITLE
Rebase 1.5.2

### PR DESCRIPTION
**Pull request by celebdor**
First version of moving to 1.5.2 and using vendored go modules.

### CODE REVIEW

**Comment by celebdor** [comment]
I suspect ci/prow/unit runs with go < 1.12 which is now necessary to build.

**Comment by celebdor** [comment]
@ironcladlou @smarterclayton Please, note that the dns operator should change the [Corefile to use the forward plugin](https://github.com/kubernetes/kubernetes/issues/73254). Otherwise the e2e tasks will fail because the proxy plugin is not enabled.

**Comment by ironcladlou** [comment]
https://github.com/openshift/cluster-dns-operator/pull/123 should remove the `proxy` plugin dependency and get the e2e tests working.

**Comment by ironcladlou** [comment]
@celebdor 
>I suspect ci/prow/unit runs with go < 1.12 which is now necessary to build. Output in my machine of running make test:

I think we need to update the openshift Dockerfile here to use 1.12 builder images, and update the [CI configs](https://github.com/openshift/release/tree/master/ci-operator/config/openshift/coredns) as well

**Comment by celebdor** [comment]
> @celebdor
> 
> > I suspect ci/prow/unit runs with go < 1.12 which is now necessary to build. Output in my machine of running make test:
> 
> I think we need to update the openshift Dockerfile here to use 1.12 builder images, and update the [CI configs](https://github.com/openshift/release/tree/master/ci-operator/config/openshift/coredns) as well

I sent a PR for the CI https://github.com/openshift/release/pull/4316 . The Dockerfiles I already moved to use golang 1.12 in this PR

**Pull request merged**
