### PR TITLE
Bug 1807234: Update coredns-mdns vendoring

### PR DESCRIPTION
**Pull request by cybertron**
A problem was fixed in coredns-mdns and we need to update the vendoring to pull it in. See #24 for details.

### CODE REVIEW

**Comment by cybertron** [comment]
/retest

Looks like rate limiting errors.

**Comment by ironcladlou** [comment]
@cybertron if you've tested this I can tag it — let me know if you're satisfied

**Comment by cybertron** [comment]
@ironcladlou Yep, I've verified that this does what we need locally. Should be good to go.

**Comment by ironcladlou** [comment]
@knobunc @smarterclayton not sure what's up with approvers here... can one of your try? I'm on the list...

**Comment by ironcladlou** [comment]
Hopefully https://github.com/openshift/release/pull/7460 fixes the approver issues

**Pull request merged**
