### PR TITLE
OCPBUGS-19805: UPSTREAM: <carry>: openshift: Fix OCPBUGS-19805

### PR DESCRIPTION
**Pull request by gcs278**
Fixes OCPBUGS-19805: fix port panic https://github.com/coredns/coredns/pull/6179

### CODE REVIEW

**Comment by Miciah** [comment]
Thanks!
/approve
/lgtm
This is a low-risk change that only adds some nil checks.  
/label backport-risk-assessed

**Comment by gcs278** [comment]
disruption test failures
/test e2e-aws-ovn-upgrade

**Comment by gcs278** [comment]
must gather failure
/test e2e-aws-ovn

pod can not be created
/test e2e-aws-ovn-upgrade

**Comment by gcs278** [comment]
cluster install failed
/test e2e-aws-ovn
/test e2e-aws-ovn-upgrade

**Comment by gcs278** [comment]
unrelated failure: `oc debug ensure it works with image streams`
/test e2e-aws-ovn

**Pull request merged**
