### PR TITLE
openstack: Add mdns plugin for coredns static pods

### PR DESCRIPTION
**Pull request by trown**
The openstack team is working on removing our single point of failure VM which hosts the etcd service records for the cluster. We have adopted the approach from KNI team of using coredns static pods running on every master. This requires an mdns plugin that they developed. This patch adds that plugin. This will allow us to remove our custom coredns image from https://github.com/openshift/machine-config-operator/pull/740

### CODE REVIEW

**Comment by bcrochet** [comment]
Can someone take a look at this patch?

**Comment by bcrochet** [comment]
This is also needed by Metal3

**Comment by celebdor** [comment]
Made a new version now that coredns-mdns is in github.com/openshift https://github.com/openshift/coredns/pull/14

**Comment by trown** [comment]
Closing in favor of https://github.com/openshift/coredns/pull/14

**Pull request closed without merging**
