### PR TITLE
OCPBUGS-36454: Rename Dockerfile.openshift.rhel7 to Dockerfile.ocp

### PR DESCRIPTION
**Pull request by ashwindasr**
Refactor name to `Dockerfile.ocp` as a better, version independent, alternative since contents are actually rhel9. 

CI: https://github.com/openshift/release/pull/53933

Please follow up with other changes in this/other repos if necessary. ART has setup the necessary [fallbacks](https://github.com/openshift-eng/ocp-build-data/pull/5039), but only for 4.17, if backporting this PR, please give us a heads up.

### CODE REVIEW

**Comment by candita** [comment]
/hold

@ashwindasr can you please determine the nature of the failure in the `images` test?

> ERRO[2024-07-02T17:58:56Z] Some steps failed:                           
> ERRO[2024-07-02T17:58:56Z] 
>   * could not run steps: step coredns failed: error occurred handling build coredns-amd64: the build coredns-amd64 failed after 1m10s with reason ManageDockerfileFailed: Failed to prepare the dockerfile for the build.

**Comment by ashwindasr** [comment]
@candita The release PR has the merge first (https://github.com/openshift/release/pull/53933), attached in description.

After that if we rerun the tests, it should pass

**Comment by ashwindasr** [comment]
/close

Image owners are working on a rename, and let ART know once they are ready.

**Pull request closed without merging**
