### PR TITLE
OCPBUGS-7558: Merge 1.10.1

### PR DESCRIPTION
**Pull request by gcs278**
Rebased to CoreDNS 1.10.1

I made this PR using the same process as https://github.com/openshift/coredns/pull/76, https://github.com/openshift/coredns/pull/73, https://github.com/openshift/coredns/pull/52, https://github.com/openshift/coredns/pull/60, and https://github.com/openshift/coredns/pull/70:

1. `git remote update`
2. `git checkout v1.10.1`
3. `git checkout -b merge-1.10.1-tmp`
4. `git checkout origin/master`
5. `echo 'merge coredns/coredns v1.10.1' | git commit-tree 'merge-1.10.1-tmp^{tree}' -p HEAD -p merge-1.10.1-tmp -F -`
`8b626bf76c57b2373ea1f897fb9d13e95d4f456d`
6. `git branch merge-1.10.1 8b626bf76c57b2373ea1f897fb9d13e95d4f456d`
7. `git checkout merge-1.10.1`
8. `git rev-list --reverse --no-merges ead3b6507d7bd2fc3e67b79d8ff0dff296396bac..origin/master | git cherry-pick --stdin`
Note: `ead3b6507d7bd2fc3e67b79d8ff0dff296396bac` is the merge commit from the last merge https://github.com/openshift/coredns/pull/76
9. My merge commit from the above process was commit https://github.com/openshift/coredns/commit/8b626bf76c57b2373ea1f897fb9d13e95d4f456d

Before the rebase, we had the following commits:

```
git --no-pager log --oneline --no-merges ead3b6507d7bd2fc3e67b79d8ff0dff296396bac..origin/master
d18012ca2 Updating coredns images to be consistent with ART Reconciling with https://github.com/openshift/ocp-build-data/tree/ef52fa34ff45201392333743c99c4b25b52fe724/images/coredns.yml
47040eaf9 UPSTREAM: <carry>: openshift: Remove UDP Payload size hardcoding to 2048 on cache upstream refreshes. Don't override EDNS0 OPT RR, created by the bufsize plugin. Also, set default upstream UDP Payload to 512 if EDNS0 OPT RR doesn't exist.
fce0690b1 Updating coredns images to be consistent with ART Reconciling with https://github.com/openshift/ocp-build-data/tree/b44f15ec9e84d1831eac81f8c757b3bed985dbeb/images/coredns.yml
b912bfdb7 UPSTREAM: <carry>: openshift: Revert "Revert "add wildcard warnings (#5030)" (#5167)"
912fc2628 UPSTREAM: <carry>: openshift: Revert "remove wildcard query functionality (#5019)"
1b37b38eb UPSTREAM: <carry>: openshift: Disable dependabot
d922347b8 UPSTREAM: <carry>: openshift: Vendor required modules
785e85831 UPSTREAM: <carry>: openshift: .gitignore: Properly ignore coredns binary
d27bea2c2 UPSTREAM: <carry>: openshift: Make coredns exclusion more specific
a61557c4a UPSTREAM: <carry>: openshift: Add a `make test` target
c288614cf UPSTREAM: <carry>: openshift: Add product build config
d2a14b4f5 UPSTREAM: <carry>: openshift: Add OWNERS

```
I edited the "Vendor required modules" commit by running go mod vendor and go mod tidy and amended commit `1d2d4f767 UPSTREAM: <carry>: openshift: Vendor required modules`.

I squashed/merged the following commit into the existing "Add product build config" commit:
```
d18012ca2 Updating coredns images to be consistent with ART Reconciling with https://github.com/openshift/ocp-build-data/tree/ef52fa34ff45201392333743c99c4b25b52fe724/images/coredns.yml
fce0690b1 Updating coredns images to be consistent with ART Reconciling with https://github.com/openshift/ocp-build-data/tree/b44f15ec9e84d1831eac81f8c757b3bed985dbeb/images/coredns.yml
```

I dropped the UDP Payload/Bufsize hardcoding fix commit because the hardcoding issues were resolved via https://github.com/coredns/coredns/pull/5671:
```
47040eaf9 UPSTREAM: <carry>: openshift: Remove UDP Payload size hardcoding to 2048 on cache upstream refreshes. Don't override EDNS0 OPT RR, created by the bufsize plugin. Also, set default upstream UDP Payload to 512 if EDNS0 OPT RR doesn't exist.
```

I dropped wildcard-query support related carry patches as they were [deprecated in OCP 4.12]:(https://docs.openshift.com/container-platform/4.12/release_notes/ocp-4-12-release-notes.html#ocp-4-12-ne-deprecations):
```
b912bfdb7 UPSTREAM: <carry>: openshift: Revert "Revert "add wildcard warnings (#5030)" (#5167)"
912fc2628 UPSTREAM: <carry>: openshift: Revert "remove wildcard query functionality (#5019)"
```

No merge conflicts.

### CODE REVIEW

**Comment by gcs278** [comment]
TestExternal Unit Test Failed. I have since fixed test case https://github.com/openshift/coredns/pull/88/files#diff-da18049bd54614e58c58fe61a84e72300d8208c2290282f776101bf7c2bda876R35 that now produces the right RCode.

**Comment by melvinjoseph86** [comment]
Verified using pre merge image
melvinjoseph@mjoseph-mac Downloads % oc get clusterversion
NAME      VERSION                                                   AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.13.0-0.ci.test-2023-02-16-051433-ci-ln-m7fzss2-latest   True        False         119m    Cluster version is 4.13.0-0.ci.test-2023-02-16-051433-ci-ln-m7fzss2-latest

melvinjoseph@mjoseph-mac Downloads % oc exec $(oc get pods -n openshift-dns --no-headers | awk '{print $1}' | head -1) -n openshift-dns -c dns -- bash -c "/usr/bin/coredns --version"
oc get co
CoreDNS-1.10.1
linux/amd64, go1.19.4,

**Comment by gcs278** [comment]
Update: Dropped Wildcard support per release notes in 4.12 stating they are officially deprecated: https://docs.openshift.com/container-platform/4.12/release_notes/ocp-4-12-release-notes.html#ocp-4-12-ne-deprecations

**Comment by cybertron** [comment]
/lgtm

metal-ipi passed so it looks like we're good with this change.

**Pull request merged**
