### PR TITLE
OCPBUGS-36454: Rename Dockerfile.openshift.rhel7 to Dockerfile.ocp

### PR DESCRIPTION
**Pull request by grzpiotrowski**
Rename `Dockerfile.openshift.rhel7` to a version independent name - `Dockerfile.ocp`.
This aims to address the discrepancy between the Dockerfile name and its contents which refer to rhel9 at the moment.

Coordinated with:

- merging the PR https://github.com/openshift/release/pull/55353 first
- ART merging https://github.com/openshift-eng/ocp-build-data/pull/5266 once this is merged.

### CODE REVIEW

**Comment by grzpiotrowski** [comment]
/test all

Tests failed but marked as successful with `Context retired without replacement.` description. `rerun` did not trigger them.

**Comment by candita** [comment]
Needs https://github.com/openshift/release/pull/55353 to merge first.

/hold

**Comment by grzpiotrowski** [comment]
/retest

https://github.com/openshift/release/pull/55353 merged, expecting tests to pass now.

**Comment by alebedev87** [comment]
Thanks @grzpiotrowski!

/lgtm
/approve

**Comment by grzpiotrowski** [comment]
/unhold

https://github.com/openshift-eng/ocp-build-data/pull/5265 is ready to go once this merges

**Comment by ashwindasr** [comment]
/hold

Once all tests pass, I'll unhold so that we can get this and the haproxy one in around the same time. Followed by https://github.com/openshift-eng/ocp-build-data/pull/5265

**Comment by ashwindasr** [comment]
/unhold

Created a seperate PR to merge in ocp-build-data

**Pull request merged**
