### PR TITLE
Bump to coredns/coredns v1.3.1

### PR DESCRIPTION
**Pull request by bbrowning**
This bumps our fork to coredns/coredns v1.3.1 while maintaining our patches as well.

Specifically:
- Our custom Dockerfiles are unchanged
- Kubernetes client version is unchanged
- All deps are vendored, even the ones upstream marks as ignored - in the same spirit as #1
  - this required overrides in Gopkg.toml to lock to the exact versions as upstream - the resolved versions without overrides differed only by patch release from what upstream coredns uses but that was enough to cause compilation errors

This also adds a new patch to our that adds a `make test` target back to the `Makefile`. Upstream got rid of the `test` target. We could choose to drop this patch, but there's not another target that easily exposes running tests that don't depend on a running etcd server.

### CODE REVIEW

**Comment by ironcladlou** [comment]
Awesome work, thanks. One last thought: what about introducing a bespoke Makefile containing the test target we want rather than patching the upstream file? The CI job could be configured to include an execution of make against the file.

Worth it?

/cc @openshift/sig-network-edge

**Comment by bbrowning** [comment]
A new Makefile to avoid future merge conflicts may not be a bad idea. But merges would still need to pull in any relevant changes as far as test suites, where tests live, how they're run, etc into that new Makefile. Would it be better to get alerted to that fact via a merge conflict or to manually keep an eye on it?

And, a new Makefile will require adjustment to ci-operator in the openshift/release repo for this component, right? That's the main reason I didn't do anything in this PR as that would have prevented Prow from being able to run the tests here.

**Comment by ironcladlou** [comment]
@bbrowning 
>A new Makefile to avoid future merge conflicts may not be a bad idea. But merges would still need to pull in any relevant changes as far as test suites, where tests live, how they're run, etc into that new Makefile. Would it be better to get alerted to that fact via a merge conflict or to manually keep an eye on it?
And, a new Makefile will require adjustment to ci-operator in the openshift/release repo for this component, right? That's the main reason I didn't do anything in this PR as that would have prevented Prow from being able to run the tests here.

Good points. Let's keep it simple with what you already have.

/lgtm

**Comment by ironcladlou** [comment]
@smarterclayton oh yeah, we don't patch OWNERS 😁 

How do you want to manage merging?

**Comment by smarterclayton** [comment]
Replace owners.

Delete existing Owners in one commit and then create another in the next
file.

On Feb 7, 2019, at 11:19 AM, Dan Mace <notifications@github.com> wrote:

@smarterclayton <https://github.com/smarterclayton> oh yeah, we don't patch
OWNERS 😁

How do you want to manage merging?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/coredns/pull/6#issuecomment-461494396>, or mute
the thread

**Comment by bbrowning** [comment]
Several e2e tests failed on that run, but from initial digging it looks like a couple of known flaking tests and some known manifest digest issues that sometimes crop up. I'll kick off the e2e tests again and see if the results repeat.

/test e2e-aws

**Pull request merged**
